# Generated by Django 5.0.1 on 2024-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_whatsapp_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompanymapping',
            name='confirmation_token',
        ),
        migrations.AddField(
            model_name='usercompanymapping',
            name='is_user_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercompanymapping',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
