# Generated by Django 5.0.1 on 2024-02-01 12:46

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_department_month_year_reportname_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=company.models.company_upload_path),
        ),
    ]
