# Generated by Django 5.0.1 on 2024-02-01 14:23

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=company.models.FileUpload.dynamic_upload_path),
        ),
    ]
